language: ruby
rvm:
  - 1.8.7
  - 1.9.3
# TODO: make this work with the regular rake command
script: "bundle exec rake spec"
gemfile:
  - Gemfile
before_script:
  - mysql -e 'create database database_cleaner_test;'
  - psql -c 'create database database_cleaner_test;' -U postgres
  - cp db/sample.config.yml db/config.yml
