language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
script: "bundle exec rake"
gemfile:
  - Gemfile
before_install:
  - gem install bundler -v 1.11.2
before_script:
  - mysql -e 'create database database_cleaner_test;'
  - psql -c 'create database database_cleaner_test;' -U postgres
  - cp db/sample.config.yml db/config.yml
services:
  - redis-server
  - mongodb
  - neo4j
